FROM nginx:alpine

# Rimuovi la config di default e metti la nostra
RUN rm -rf /usr/share/nginx/html/*
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia direttamente la cartella dist generata in locale sul Mac
COPY dist/frontend/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]