/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Appetizing Adventure — Material Design 3 color tokens
        'primary': '#ab2f0a',
        'on-primary': '#ffffff',
        'primary-container': '#cd4722',
        'on-primary-container': '#fffbff',
        'primary-fixed': '#ffdbd2',
        'primary-fixed-dim': '#ffb4a1',
        'on-primary-fixed': '#3c0800',
        'on-primary-fixed-variant': '#881f00',
        'inverse-primary': '#ffb4a1',
        'surface-tint': '#ae310d',

        'secondary': '#3a674f',
        'on-secondary': '#ffffff',
        'secondary-container': '#bceecf',
        'on-secondary-container': '#406d55',
        'secondary-fixed': '#bceecf',
        'secondary-fixed-dim': '#a1d1b4',
        'on-secondary-fixed': '#002112',
        'on-secondary-fixed-variant': '#224f39',

        'tertiary': '#795600',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#986d00',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdea8',
        'tertiary-fixed-dim': '#ffba20',
        'on-tertiary-fixed': '#271900',
        'on-tertiary-fixed-variant': '#5e4200',

        'surface': '#fcf9f4',
        'surface-dim': '#dcdad5',
        'surface-bright': '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede9',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'surface-variant': '#e5e2dd',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#59413b',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f3f0eb',

        'outline': '#8d7169',
        'outline-variant': '#e1bfb7',

        'background': '#fcf9f4',
        'on-background': '#1c1c19',

        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '1rem',
        'gutter-desktop': '1.5rem',
        'margin': '1rem',
        'margin-desktop': '2.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-sm':  ['11px', { lineHeight: '14px', fontWeight: '700' }],
        'label-md':  ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-lg':  ['14px', { lineHeight: '18px', fontWeight: '700' }],
        'body-sm':   ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md':   ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-lg':   ['16px', { lineHeight: '26px', fontWeight: '500' }],
        'headline-sm':        ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'headline-md':        ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-lg':        ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-xl':        ['40px', { lineHeight: '48px', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
