stages:
  - deploy

variables:
  DOCKER_IMAGE_FE: "app1-frontend:latest"

deploy_frontend:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image con i file statici pre-compilati..."
    - docker build -t $DOCKER_IMAGE_FE ./frontend
    - cd /home/alessandrodominici/stacks/app1
    - docker-compose up -d --force-recreate frontend
    - echo "Deploy completato su https://app1.alessandrodominici.dev"
  only:
    - main
  tags:
    - raspberry
